<a href="https://colab.research.google.com/github/acaropi/Curso-Ciencia-de-Datos-/blob/main/tarea_01_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [1]:
# Tu respuesta aquí

nombre = 'Carolina'
edad = 31

print("Hola, me llamo:", nombre, "y tengo", edad, "años")

Hola, me llamo: Carolina y tengo 31 años


In [2]:
# Por practicar agrego otra manera con f-strings (permiten mezclar texto y variables sin comas)

nombre = 'Carolina'
edad = 31

print(f"Hola, me llamo {nombre} y tengo {edad} años")

Hola, me llamo Carolina y tengo 31 años


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [3]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí (Esto es para recordar - acceder con slicing e Indexación en Python las listas comienzan en la posición 0 y al último elemento se puede acceder con -1 )

#Imprime el primer y el último elemento.
print('Primer número de la lista:', numeros[0])
print('último número de la lista:', numeros[-1])

#Imprime los tres primeros elementos usando slicing.
print('Primeros tres números de la lista:', numeros[:3])

#Agrega el número 99 al final de la lista.

numeros.append(99)

print(numeros)

Primer número de la lista: 10
último número de la lista: 15
Primeros tres números de la lista: [10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


In [4]:
#Para practicar --
numeros = [10, 25, 3, 47, 8, 15]

#agregar al inicio -  lista.insert(posición, valor)

numeros.insert(0,99)
print(numeros)

#reemplazar un dato donde conozco la posición - ejem: cambiar el 10 (posición 1) por 100.

numeros[1] = 100
print(numeros)

#reemplazar un dato donde no conozco la posición

indice = numeros.index(15)  #Busca dónde está el 15
print(indice)  #Si sólo quiero saber en qué posisiciones está el valor
numeros[indice] =200   #Si lo quiero cambiar por un valor especifico
print(numeros)

[99, 10, 25, 3, 47, 8, 15]
[99, 100, 25, 3, 47, 8, 15]
6
[99, 100, 25, 3, 47, 8, 200]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [5]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
estudiante["promedio"]

if estudiante["promedio"]>= 6:
  print("Aprobado")
else:  #Importante la indentación
    print("Reprobado")

Aprobado


In [6]:
#Para práctica quiero hacer el ejercicio si fueran muchos estudiantes


estudiantes1 = [
    {"nombre": "Ana", "carrera": "Ingeniería", "promedio": 7},
    {"nombre": "Luis", "carrera": "Matemáticas", "promedio": 5},
    {"nombre": "Carolina", "carrera": "Ciencia de Datos", "promedio": 6.5}
]

for estudiantes1 in estudiantes1:
    if estudiantes1["promedio"] >= 6:
        print(estudiantes1["nombre"], "Aprobado")
    else:
        print(estudiantes1["nombre"], "Reprobado")

Ana Aprobado
Luis Reprobado
Carolina Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [7]:
# Tu respuesta aquí def (para definir la función)

#CALCULA
def calcular_area(base, altura):  # (base, altura) dato que entra
  return base*altura/2  #Dato que sale

area = calcular_area(5,8)  #Especifico los varores de base y altura
print(area)  #Imprimo el resultado

20.0


In [8]:
#Realizo otro ejemplo de función - Covertir de °C a F -  Fórmula: F=(C×9/5)+32

#CONVIERTE
def celsius_a_fahrenheit(celsius):
  return (celsius*9/5)+32

resultado = celsius_a_fahrenheit(25)
print(resultado)

#DECIDE
def es_mayor_de_edad(edad):
    if edad >= 18:
        return "Es mayor de edad"
    else:
        return "Es menor de edad"

print(es_mayor_de_edad(20))
print(es_mayor_de_edad(15))


77.0
Es mayor de edad
Es menor de edad


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [9]:
# Tu respuesta aquí # Una "list comprehension" es un for más corto
# El cuadrado de un número es (n * n) o (n^2) que este símbolo para elevar "^" en Python es (n**n)

cuadrados = [n**2 for n in range(1, 11)]  # Para cada n del rango del 1 al 10 guarda su cuadrado en una lista
print(cuadrados)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [10]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [11]:
# Tu respuesta aquí
#Arreglo con los valores

arr1 = np.array([1.5, 2.5, 3.5, 4.5])
print(arr1)
print("shape",arr1.shape)
print("shape",arr1.dtype)

#Matriz 3 filas × 4 columnas
# Para matrices de ceros se usa np.zeros((filas, columnas)).

matriz_ceros = np.zeros((3,4))
print(matriz_ceros)

print("Shape:", matriz_ceros.shape)
print("Dtype:", matriz_ceros.dtype)

#arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando linspace)
#np.linspace(inicio, fin, cantidad)

arr_linspace = np.linspace(0,1,6)

print(arr_linspace)
print("Shape:", arr_linspace.shape)

[1.5 2.5 3.5 4.5]
shape (4,)
shape float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Dtype: float64
[0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,)


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [12]:
a = np.arange(1, 13)
print(a)

# Tu respuesta aquí

# Convertir el arreglo en una matriz de 3 × 4 con reshape

matriz = a.reshape(3, 4)
print("------------------------------")
print(matriz)

#Imprimir el valor máximo y mínimo
print("------------------------------")
print("Valor máximo:", matriz.max())
print("Valor mínimo:", matriz.min())

#Obtener la posición (índice) del valor máximo

fila, columna = np.unravel_index(matriz.argmax(), matriz.shape)
print("------------------------------")
print("Posición del valor máximo → fila:", fila, ", columna:", columna)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------
Valor máximo: 12
Valor mínimo: 1
------------------------------
Posición del valor máximo → fila: 2 , columna: 3


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [14]:
# Tu respuesta aquí

 #Crear dos arreglos de 5 elementos con valores entre 1 y 20
arreglo1 = np.random.randint(1, 21, size=5)
arreglo2 = np.random.randint(1, 21, size=5)

# Operaciones elemento por elemento
suma = arreglo1 + arreglo2
resta = arreglo1 - arreglo2
multiplicacion = arreglo1 * arreglo2

# Imprimir resultados
print("Arreglo 1:", arreglo1)
print("Arreglo 2:", arreglo2)
print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)


Arreglo 1: [18  7 11 16 13]
Arreglo 2: [17  9  4 13  4]
Suma: [35 16 15 29 17]
Resta: [ 1 -2  7  3  9]
Multiplicación: [306  63  44 208  52]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [15]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí

# Arreglo de notas
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Indexación booleana: notas mayores o iguales a 6
notas_aprobadas = notas[notas >= 6]

# Imprimir resultado
print("Notas mayores o iguales a 6:", notas_aprobadas)


Notas mayores o iguales a 6: [ 8.5  6.   9.2  7.8 10. ]
